version: '2'

services:
  mysql:
    image: mysql:latest 
    ports: 
      -"3306:3306"
    volumes:
      -./mysql-data:/var/lib/mysql

  # Todo el servicio 'mysql' es lo mismo que correr... 'docker container run -p 3306:3306 -v $(pwd)/mysql-data:/var/lib/mysql mysql:latest'

  
  api:
    image: alexramosglz/visitor
    ports:
      -"8080:8080"
    
  