apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visitor-ingress
  namespace: default
spec:
  rules:
    - host:
        visitor.com

        # Los request que sean hechos a "visitor" host seran redirigidos
        # al internal service
        #
        # Mapear domain name al IP del nodo que hara la funcion de entrypoint

      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              # "backend" es basicamente el target a donde el trafico es redirigido

              service:
                # El "service" tiene que conincidir con el nombre del Service al que se esta
                # apuntando

                name: visitor-service
                port:
                  number: 3000
          - pathType: Prefix
            path: "/test"
            backend:
              service:
                name: test-service
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: visitor-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: visitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitor-deploy
  namespace: default
spec:
  selector:
    matchLabels:
      app: visitor
  template:
    metadata:
      labels:
        app: visitor
    spec:
      containers:
        - name: visitor
          image: alexramosglz/visitor
          ports:
            - containerPort: 3000
