#########################################################
##                                                     ##
##                     Ingress                         ##
##                                                     ##
#########################################################

# Ingress es un recurso de Kubernetes que permite el acceso a nuestro
# k8s service desde el exterior del cluster. Se configura el acceso creando una coleccion de
# reglas que definen cuales inbound connections pueden acceder a que servicios.
#
# Esto permite declarar routing roules en un solo lugar...
#
# Por ejemplo, es posible que desee enviar request a example.com/api/v1/ al Service api-v1,
# y otro request a example.com/api/v2/ al Service api-v2.
#

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations: 
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: example.com
      
        # El campo "host" es el nombre de dominio que se usara para acceder al Ingress.
        #
        
      http:
        paths:
          - path: /apple
            pathType: Prefix
            backend:
              service:
                name: apple-service
                port:
                  number: 5678
          - path: /banana
            pathType: Prefix
            backend:
              service:
                name: banana-service
                port:
                  number: 5678

---
apiVersion: v1
kind: Pod
metadata:
  name: apple-app
  labels:
    app: apple
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - "-text=Hello from Apple"
---
apiVersion: v1
kind: Service
metadata:
  name: apple-service
spec:
  selector:
    app: apple
  ports:
    - port: 5678

---
kind: Pod
apiVersion: v1
metadata:
  name: banana-app
  labels:
    app: banana
spec:
  containers:
    - name: banana-app
      image: hashicorp/http-echo
      args:
        - "-text=banana"

---
kind: Service
apiVersion: v1
metadata:
  name: banana-service
spec:
  selector:
    app: banana
  ports:
    - port: 5678 # Default port for image
