
#########################################################
##                                                     ##
##                    Secret                           ##
##                                                     ##
#########################################################

apiVersion: v1
kind: Secret

  # Secret es similar a un ConfigMap, pero se usa para almacenar datos sensibles
  # como contraseñas, tokens de acceso, etc. Esta informacion de otra forma
  # puede estar almacenada en un Pod o especificada en un container image.
  #
  # Usando Secret se puede evitar que esta informacion sea inclueda en el codigo de 
  # la aplicacion.

metadata:
  name: dotfile-secret
type: Opaque

  # El campo "type" es opcional, pero se puede usar para especificar el tipo de Secret.
  # El tipo "Opaque" es el tipo por defecto y se usa para almacenar datos arbitrarios.
  # 
  
data:
  .secret-file: U2VjcmV0byBkZSBhbW9yCg==

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfile-pod
spec:
  volumes:
    - name: secret-volume
      secret:

        # El campo "secret" es el typo de volumen que se usa para montar un Secret
        # en un Pod.

        secretName: dotfile-secret
        
          # El campo "secretName" es el nombre del Secret que esta en el namespace
          # actual del pod.
          #
          # el valor de este campo debe coincidir con el nombre del Secret que se definio
          # en el Secret.
  containers:
    - name: dotfile-test-container
      image: nginx:latest
      #command: ["ls", "-l", "/etc/secret-volume"]
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume